### ISSUE TITLE
Пропозиції

### ISSUE THREAD

**Issue by lookMyCode** [ddosSepar/ddosSepar.github.io#2]
Пропоную накидати пропозиції.

Почну я.

Мапа зосередження ворожих військ. Побачив? Зазначив де і додав опис. Колір маркеру буде змінюватись з часом, щоб візуально орієнтуватись скільки часу минуло. Чи є щось подібне?

Але не знаю як захистити від спаму :(

**Comment by ddosSepar** [comment]
Для початку хоча б це))

**Comment by lookMyCode** [comment]
@ddosSepar то може зробити оголошення? Я ангуляр розробник, але можу и бек на нести писати, володію SQL
